[package]
name = "json-rust"
version = "0.1.0"
authors = ["zanchi <emzanchi@gmail.com>"]

[dependencies]
serde_json = "1.0.32"
serde = "1.0.80"
serde_derive = "1.0.80"
hyper = "0.12.13"
futures = "0.1.25"
